### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by gbbauto** [Qard/node-isolated-bcrypt#1]
Firstly, thanks for making this package.

but npm is not allowing me to install due to checksum error

$ mkdir tmp
$ cd tmp/
$ npm install isolated-bcrypt
npm http GET https://registry.npmjs.org/isolated-bcrypt
npm http 304 https://registry.npmjs.org/isolated-bcrypt
npm http GET https://registry.npmjs.org/isolated-bcrypt/-/isolated-bcrypt-0.0.1.tgz
npm http 200 https://registry.npmjs.org/isolated-bcrypt/-/isolated-bcrypt-0.0.1.tgz
npm ERR! Error: shasum check failed for /home/ec2-user/tmp/npm-3110-Sjdt0hv7/1392054849778-0.8002762936521322/tmp.tgz
npm ERR! Expected: 78772cb1d18caea5f053c03abe6e3891039ca8fd
npm ERR! Actual:   685730fe5b1c1d1a7ef0fad5447dc76f0cc9863a
npm ERR!     at /usr/local/node-v0.11.11-linux-x64/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/node-v0.11.11-linux-x64/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:126:20)
npm ERR!     at _stream_readable.js:896:16
npm ERR!     at process._tickCallback (node.js:664:11)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/isaacs/npm/issues

npm ERR! System Linux 3.4.73-64.112.amzn1.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "isolated-bcrypt"
npm ERR! cwd /home/ec2-user/work/tmp
npm ERR! node -v v0.11.11
npm ERR! npm -v 1.3.25
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ec2-user/work/tmp/npm-debug.log
npm ERR! not ok code 0

**Comment by Qard** [comment]
npm doesn't seem to like the large binary package. I'll have to see if I can host the binaries separately and write and install script to pull them down.

You could try using a github dependency by changing the version to `qard/isolated-bcrypt` for now.

**Comment by gbbauto** [comment]
thanks, I got it from github
